### ISSUE TITLE
After mac sleep (maybe also hibernation on windows), the node may not be able to recover without a restart

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#1070]
While the GUI node is running all the time, when I'm done work, I close my mac and get out of my office. Later when I open the mac. I noticed that under certain circumstances, the node is unable to reconnect to nodes. The only way to make it work is by closing the node and reopenning it.

The symptoms I'm facing is that there are no peers, and the node is not reconnecting to peers. The only message I see in the logs is:

```
[2023-07-22T09:10:07Z ERROR p2p::peer_manager] resolve DNS seed failed: failed to lookup address information: nodename nor servname provided, or not known
```

**Comment by pavel-kokolemin** [comment]
I have not been able to reproduce this issue. I tried several times on both a Macbook and a Windows laptop. As soon as the OS wakes up from sleep, the GUI starts reconnecting and after 30-60 seconds 6..8 peers are connected.

**Comment by TheQuantumPhysicist** [comment]
I'm closing this as I also can't reproduce it. I'll reopen it if it happens again.
