### ISSUE TITLE
Block production should not produce blocks if chainstate is in initial block download mode

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#1071]
Initial block download means that the chainstate is far from being synced. Block production should call the function ChainstateInterface::info() to know whether the chainstate is ready to have new blocks produced.

**Comment by TheQuantumPhysicist** [comment]
@alfiedotwtf I believe this is done, right?

**Comment by alfiedotwtf** [comment]
Yep. The commits are from 3665b4a383d to ee3b7271e6
