### ISSUE TITLE
We should have a way to list all available staking pools, with information on their offers

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#1103]
Whether this should go into the API server or the node is a good question. However, we need this information so that delegators can get information on where to delegate.

The idea is that there should be some kind of listing of all available pools, including their balances, delegation and percentage they take from the rewards. This should present a free market for delegators where they can choose the pool with the best offer, besides this being important to know what pools are out there anyway.

**Comment by azarovh** [comment]
I could add the method to the `ChainstateInterface`. Should be pretty straightforward.

**Comment by TheQuantumPhysicist** [comment]
Done.
