### ISSUE TITLE
Use checked functions for all uint operations

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#1218]
All types created from `common/src/uint/impls.rs` must use checked operations only, the same way as Amount does.

**Comment by alfiedotwtf** [comment]
Should this be extended for all math operations in code? i.e  something like `grep -P '[+-/%]'` should return no results?

**Comment by TheQuantumPhysicist** [comment]
> Should this be extended for all math operations in code? i.e something like `grep -P '[+-/%]'` should return no results?

I doubt this is really feasible. Those symbols can mean other things.
