### ISSUE TITLE
Improve BlockError

### ISSUE THREAD

**Issue by sinitcin** [mintlayer/mintlayer-core#126]
According to @iljakuklic comment https://github.com/mintlayer/mintlayer-core/pull/124#discussion_r837198649 we should add `BlockError::StorageFailure`.

Also, we should add other errors and classify them as recoverable or irrecoverable.

**Comment by sinitcin** [comment]
@altonen mentioned in https://github.com/mintlayer/mintlayer-core/pull/124#discussion_r838109714 that we should have more errors here

**Comment by sinitcin** [comment]
@iljakuklic mentioned in https://github.com/mintlayer/mintlayer-core/pull/124#discussion_r840427440 that we need to figure out which errors should be propagated to the caller and which should induce panic.

**Comment by TheQuantumPhysicist** [comment]
Done in #220
