### ISSUE TITLE
Mismatch for SHA256 checksum

### ISSUE THREAD

**Issue by genjieth** [mintlayer/mintlayer-core#1383]
On the page: https://www.mintlayer.org/en/download/
For Mac OS, Intel users
For the binary Wallet Address Generator

There is a mismatch between the SHA256 checksum provided and the actual SHA256 checksum obtained via shasum -a 256 on my end.

Node Deamon and Wallet CLI match the ones provided.

**Comment by TheQuantumPhysicist** [comment]
I appreciate your submission, we'll look into it (I'll pass it on). But please don't report website-related problems here on mintlayer-core repo. This isn't the right place. Try to communicate with our social channels or the website repo (if it's public). The engineers in this repo don't deal with these problems.
