### ISSUE TITLE
Wallet Create staking pool command argument format for margin per thousand

### ISSUE THREAD

**Issue by anyxem** [mintlayer/mintlayer-core#1419]
Tested platforms: mac os and ubuntu

When user create staking pool and trying to set margin to 1000 wallet return next error
```
Wallet> createstakepool 40000 5 1000
Invalid input: Failed to parse margin ratio. The decimal must be in the range [0.001,1.000] or [0.1%,100%]
```

assuming that value should me between 0.001 and 1.000 however value `10` works well. Need to check validation and parsing for this argument. Percent values don’t have issues

**Comment by azarovh** [comment]
I double checked the logic and tried to reproduce but it seems to work as expected producing an error for everything above 1.

```
Wallet>  createstakepool 40000 5 1000
Invalid input: Failed to parse margin ratio. The decimal must be in the range [0.001,1.000] or [0.1%,100%]
Wallet>  createstakepool 40000 5 10
Invalid input: Failed to parse margin ratio. The decimal must be in the range [0.001,1.000] or [0.1%,100%]
Wallet>  createstakepool 40000 5 2
Invalid input: Failed to parse margin ratio. The decimal must be in the range [0.001,1.000] or [0.1%,100%]
Wallet>  createstakepool 40000 5 1
Please open or create wallet file first
```

@anyxem Are you sure that's the way you created [this pool](https://explorer.mintlayer.org/pool/tpool16qpe4x4pgllt67grwr07gxevhj4z9m3003xczqvgshp8cxthetpqdjnsxc)?

**Comment by anyxem** [comment]
I used 
`Wallet> createstakepool 40000 5 10`
As a reference on wiki page. Currently it is 0.01 so maybe back to that it was working. If now that is not an issue we can close this

**Comment by TheQuantumPhysicist** [comment]
A long time ago that format used to work. But we changed it to avoid confusion. If you're sure this isn't possible now, let's close this issue.
