### ISSUE TITLE
Clarify the process for decommissioning a pool when the decommission key is from the outside

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#1424]
Currently we support adding a pool decommission key, but the process on how decommissioning works isn't clear. We should solve this before mainnet.

**Comment by TheQuantumPhysicist** [comment]
The process as I see it:

1. The staking wallet generates a message/transaction to be signed (in address, not strictly necessary). Make sure to include the decommission public key in that message. The message can have a enum serialization format so that it can be upgraded. (Maybe with a QR Code)
2. We copy this message, and paste it in the wallet that owns the decommission key
3. If no broadcast is enabled (since it's a cold wallet), the user has to copy the result and broadcast it (maybe enable QR Code)

Functions:
- `authorizepooldecommission` (print a message explaining how to proceed)
- `authorizepooldecommissionandbroadcast`

**Comment by azarovh** [comment]
implemented in #1448
