### ISSUE TITLE
Create a very long reorg test

### ISSUE THREAD

**Issue by sinitcin** [mintlayer/mintlayer-core#173]
We have to add a very long reorg test. A very long reorg implies that you create something like 2000 blocks, than you create another chain that's 2001 blocks longer, and then you make sure that it's the new state.

**Comment by azarovh** [comment]
I'm not sure that we need one. We have tests with 100 blocks depth reorg (e.g. `tests::pos_accounting_reorg::long_chain_reorg`). Making it longer would just waste execution time with no benefit.
