### ISSUE TITLE
Create a global block test framework

### ISSUE THREAD

**Issue by altonen** [mintlayer/mintlayer-core#182]
Subsystems that communicate with consensus need to be able to create new blocks and chains. Currently this is implemented inside consensus using the `BlockTestFrameWork`. This framework should be exposed, maybe through a subsystem, so other subsystems could use it to create new blocks and test their own functionality.

**Comment by iljakuklic** [comment]
I think @stanislav-tkach is currently working towards this, is that correct?

**Comment by stanislav-tkach** [comment]
I haven't seen this issue before, but Sam mentioned to me that it would be nice to reuse this "test framework" in the p2p code. It seems logical to me, but as a second step. Right now I'm concentrating solely on the chainstate tests. But I would like to tackle this issue too.

**Comment by stanislav-tkach** [comment]
Closed with https://github.com/mintlayer/mintlayer-core/pull/720.
