### ISSUE TITLE
Use utxo in TestBlockInfo

### ISSUE THREAD

**Issue by stanislav-tkach** [mintlayer/mintlayer-core#312]
See https://github.com/mintlayer/mintlayer-core/pull/299#discussion_r927465928 for the details.

**Comment by TheQuantumPhysicist** [comment]
Keep in mind that this already exists in the utxo crate but needs some maintenance and needs to be used.

**Comment by stanislav-tkach** [comment]
@azarovh I think it is useful to reference the pull request that closes the issue.

**Comment by azarovh** [comment]
The issue is not closed actually. I renamed it properly and reopened.

**Comment by TheQuantumPhysicist** [comment]
TestBlockInfo doesn't exist anymore in the chainstate test suite. This is considered over.
