### ISSUE TITLE
Check transaction size limits properly in mempool validation

### ISSUE THREAD

**Issue by royster57** [mintlayer/mintlayer-core#331]
The problem is that the header size is not fixed. So there's no way to check this properly. 
I can think of a DDoS on the mempool where someone submits transactions that have high fees, to take priority, and large is size so they're unusable. We should introduce some kind of lower bound for the header so that this can be calculated correctly.

See if you can find a way around this limitation, or slap a TODO somewhere here so that we look into later this and reference this comment.

_Originally posted by @TheQuantumPhysicist in https://github.com/mintlayer/mintlayer-core/pull/43#discussion_r934669288_

**Comment by TheQuantumPhysicist** [comment]
This should be fixed before the testnet.
