### ISSUE TITLE
Consider extracting witnesses out of transaction and making `Idable`, `Eq` and `Encode` behave consistently

### ISSUE THREAD

**Issue by iljakuklic** [mintlayer/mintlayer-core#348]
Extracting discussion from #346:

@iljakuklic 
> This whole thing points to the deeper issue that sometimes the ID determines the object entirely and sometimes not. It also comes up when calculating the ID itself, in signatures, etc., where we have to carefully avoid including witnesses but make sure to include everything else. It creates a bunch of mess. We could improve on it with some more refactoring, perhaps, where we separate witnesses and transactions a bit more, i.e. something like (heavily simplified):
> 
> ```rust
> struct BlockBody {
>     rewards: Vec<TxOutput>,
>     witnesses: Vec<Witness>,
>     transactions: Vec<Transaction>,
> }
> ```
> 
> The `Transaction` type would not include a witness. Then `Id<Transaction>` would fully determine the transaction, equality comparison could be done by comparing `Id` just like with everything else. Another type would be introduced, say `SignedTransaction`, which pairs up `Transaction` with the corresponding subsequence of witnesses. Then `Id<SignedTransaction>` would signify an id of transaction with particular set of witnesses. There are multiple valid `SignedTransaction`s for each `Transaction` because of malleability. The two Merkle roots would be derived one from a seqiuence of `Id<Transaction>` and the other one from a sequence of `Id<SignedTransaction>`. The distinction between transactions with or without witnesses and IDs thereof becomes explicit.
> 
> This means, however, departing even more from Bitcoin, although segwit is quite similar with having witnesses completely separate. Another possibility is to do it at `Transaction` level (same reasoning about IDs as above applies):
> 
> ```rust
> struct Transaction {
>     inputs: Vec<TxInput>, // Does not contain a Witness
>     outputs: Vec<TxOutput>,
>     // other stuff
> }
> struct SignedTransaction {
>    tx: Transaction,
>    witnesses: Vec<Witness>, // Exactly one per tx.inputs
> }
> ```
> 
> Or something similar. That would address a bunch of issues where we have to special case `Transaction`:
> 
> * Calculating ID of objects would reduce to just serializing and hashing
> * Comparing by ID is sufficient to fully determine equality of the object
> * Perhaps some more I've forgotten, I recall a couple of instances where this is the underlying issue.
> 
> Comments / thoughts / counter-proposals?

@TheQuantumPhysicist 
> The SignedTransaction struct is something I suggested in the engineering channel a few months ago... but I never got to it as other things with higher priority got in the way. It's not simple though because it'll create issues with the enum of versions of Transaction. Creating an interface for that is difficult. Feel free to give it a shot.
> 
> On the other hand, I don't think the SignedTransaction thing will help alleviate any of your concerns. We still have to specialize for SignedTransaction anyway, which will become the mempool transaction type because unsigned transactions don't make sense in the mempool. So we're back at square one. How are you gonna implement Eq for `WithId<SignedTransaction>`?
> 
> Separate transactions at the block level won't work, btw, because we need to bundle the witness with transactions somehow for the mempool. So we'll have SignedTransaction anyway.

@iljakuklic 
> > The SignedTransaction struct is something I suggested in the engineering channel a few months ago... but I never got to it as other things with higher priority got in the way. It's not simple though because it'll create issues with the enum of versions of Transaction. Creating an interface for that is difficult.
> 
> True, it's not going to be trivial to come up with a nice representation for this.
> 
> > On the other hand, I don't think the SignedTransaction thing will help alleviate any of your concerns. We still have to specialize for SignedTransaction anyway, which will become the mempool transaction type because unsigned transactions don't make sense in the mempool.
> 
> Well the maps would look like something like `BTreeMap<Id<Transaction>, SignedTransaction>` where `key == value.transaction().get_id()`, i.e. signed transactions addressed by transaction ID. Notice how everything is completely explicit and visible in the code. This forces you to think about what happens when a transaction with the same ID but different signature arrives, since the distinction between plain transaction and (transaction + witness) is now explicit. In general, I'd say,
> 
> > So we're back at square one. How are you gonna implement Eq for `WithId<SignedTransaction>`?
> 
> Ideally everything would behave in a consistent, predictable manner. For most objects `x, y: T` that form the blockchain, the following should hold:
> 
> 1. `(x.encode() == y.encode()) = (x == y)`
> 2. `WithId::new(x).get_id() = x.get_id()`
> 3. `(x == y) = (x.get_id() == y.get_id())`
> 
> Today, (1) and (3) don't hold for all types, although they still hold asymetrically as implications.
> 
> There would not be any special `Eq` instance for `WithId<SignedTransaction>`. You are comparing signed transactions, so the result is the same as comparing signed transactions directly, i.e. everything including witnesses. If comparison without witnesses is desired, compare `Transaction`s instead. This holds regardless the use of `WithId`. The `WithId` impl would just compare the IDs, as for all other types.

**Comment by TheQuantumPhysicist** [comment]
#454 and #462 accomplished this.
