### ISSUE TITLE
Use Id<Transaction> as key in MempoolStore

### ISSUE THREAD

**Issue by royster57** [mintlayer/mintlayer-core#349]
Somewhat unrelated to the present PR, but could the key here also be `Id<Transaction>` rather than `H256`?

_Originally posted by @iljakuklic in https://github.com/mintlayer/mintlayer-core/pull/345#discussion_r939681201_

**Comment by royster57** [comment]
`Id<Transaction>` doesn't implement `Hash` so it can't be used as is as the key to a hashmap. Should we implement this or drop the issue? I remember back in the day there was an objection to implementing `Hash` for `Id<Transaction>`, but I'm not sure what it was. Something security related, I think...

**Comment by iljakuklic** [comment]
> `Id<Transaction>` doesn't implement `Hash` so it can't be used as is as the key to a hashmap. Should we implement this or drop the issue? I remember back in the day there was an objection to implementing `Hash` for `Id<Transaction>`, but I'm not sure what it was. Something security related, I think...

Is there an issue switching it over to `BTreeMap`?

**Comment by royster57** [comment]
@iljakuklic Not really, unless we care about `contains_transaction` having amortized O(1) complexity.
