### ISSUE TITLE
Type aliases for  `Box<dyn MempoolInterface>` occurrences

### ISSUE THREAD

**Issue by royster57** [mintlayer/mintlayer-core#370]
I think there should be type aliases for all these `Box<dyn Foo>` occurrences. The fact it's a box of some dyn trait is mostly an implementation detail. No need to do it as a part of this PR

_Originally posted by @iljakuklic in https://github.com/mintlayer/mintlayer-core/pull/367#discussion_r951192200_

**Comment by TheQuantumPhysicist** [comment]
There's a type alias, but for some reason I noticed it's not public. I failed to understand what's going on there.

**Comment by TheQuantumPhysicist** [comment]
To be clear, there are aliases for these wrapper with subsystems. These are not public.
