### ISSUE TITLE
Come with a better name for p2p protocol

### ISSUE THREAD

**Issue by stanislav-tkach** [mintlayer/mintlayer-core#371]
Currently we have the following data types in the p2p crate:
```rust
pub struct Protocol {
    version: SemVer,
    protocol: ProtocolType,
}

pub enum ProtocolType {
    PubSub,
    Ping,
    Sync,
}
```
The "protocol" name is too generic, so it should be replaced with something more domain-specific.

**Comment by TheQuantumPhysicist** [comment]
I think this isn't relevant anymore. Right @stanislav-tkach ? If so, please close it.

**Comment by stanislav-tkach** [comment]
Yes, the whole protocol versioning has been removed.
