### ISSUE TITLE
p2p: Implement backpressure for channels

### ISSUE THREAD

**Issue by altonen** [mintlayer/mintlayer-core#373]

**Comment by TheQuantumPhysicist** [comment]
To clarify this, the problem here is that the channels in p2p are unbounded, so there's fear that the node can be overloaded with requests. We want to be able to handle such a situation instead of crashing the node through memory issues. This has to be studied before we decide the proper solution.

**Comment by TheQuantumPhysicist** [comment]
Related: #664
