### ISSUE TITLE
Token issuance fee represents a conflict of interest with transaction size fee

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#410]
If the token issuance fee is huge compared to the typical transaction fee caused by the size of the transaction, it basically overshadows any fees paid for the size of a transaction, which basically means that a transaction with issuance can basically contain tons of outputs and inputs since it's all free to do that in a transaction that has some token issuance.

On the other hand, if we do the obvious thing and subtract the token issuance fee when calculating size fee, we're basically working against the miners' interests, because they don't care about the token fee dynamics, but they'd be more interested transactions that have the highest fee possible per kb, regardless of issuance, where issuance increases the fee per kb significantly.

A possible solution to this problem, off the top of my head, is to limit the possible number of inputs and outputs in issuance transactions in such a way that prevents this whole problem from happening and limits the size scaling vs fee. However, this seems to be too intrusive for my taste. But maybe this is the only solution we can come up with.

**Comment by erubboli** [comment]
The idea of having a specific fee for token issuance is to reduce pollution of garbage tokens, especially when the onchain fees are negligible. On the other side we want to prevent the token issuance tx to be abused as in your example. How about summing the two? In order to issue a new token the fee is the sum of A+B where A is the flat base token issuance fee, and B is proportional to the transaction size. 

This way A prevent the abuse of new token generation and B prevent transactions to be too large (as it is in every other tx). As a miner I will always pick the tx with larger fees, but having A+B we know that token generation tx are more interesting on one side, and discouraged (more expensive) on the other.

**Comment by TheQuantumPhysicist** [comment]
> The idea of having a specific fee for token issuance is to reduce pollution of garbage tokens

No disagreement there. But the presence of a fee that isn't related to the size is the issue.

I think there might be a misunderstanding on the dynamics of this issue. Let me elaborate. For an arbitrary incoming transaction with or without issuance, the fee will, anyway, be calculated as `f=inputs-outputs` (it can't be done differently with a transaction being a vector of inputs and outputs). Once we have that number, multiple things have to happen with that number:

1. That number has to be used to make a miner prefer a transaction over the other
2. That number has to be used to decide whether a transaction is eligible for creating a token, which is typically satisfied when `f >= minimum_fee`

Currently, and also based on how bitcoin works, the fee-rate, which is the fee/kb (which can be calculated with `f/total_tx_size_in_bytes`, is the primary deciding factor on what transaction to prefer for a miner. This helps in maximizing revenue for miners (given that the size of blocks is limited). Now you have two things to consider in that context:

1. The miner wants to maximize the fees (fee-rate) he gets, which includes the issuance fee (making the fee-rate huge for issuance transactions)
2. The protocol prefers to neglect the issuance fee, because otherwise the transaction creator can make a transaction really huge and get the token issuance for free, as described in the original post.

These two can't coexist. This is the conflict.

**Comment by TheQuantumPhysicist** [comment]
A possible solution is to burn the fee instead of handing it to the block producer/miner.

**Comment by erubboli** [comment]
you are 100% right here, burning the fees is a good idea
