### ISSUE TITLE
Decide how the semantic versioning of the code will be done

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#451]
Rust 1.64 [release](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html) allows inheriting the version number. By mainnet, we should've decided how to do this versioning. Specifically, what crates we want to follow the version of the whole workspace, and whether we want a single version number for everything.

Video on this: https://www.youtube.com/watch?v=CO5Xo76CVCk

**Comment by stanislav-tkach** [comment]
I think that it is much easier to manage a single version for everything. On the other hand, it will require to publish a new version for every crate even if this particular crate hasn't been changed.
