### ISSUE TITLE
Audit secret holding data types and implement erase on drop

### ISSUE THREAD

**Issue by erasmospunk** [mintlayer/mintlayer-core#472]
Data types that hold secrets (e.g. `PrivateKey`) can leave their sensitive data in memory when `Drop`ped and when accidental copies are made.

Consider using something like [secrecy](https://docs.rs/secrecy/latest/secrecy/) that zeroes the memory when dropping.

**Comment by TheQuantumPhysicist** [comment]
This is already implemented in tari's keys, the underlying implementation, that's why we don't need to do it.

**Comment by erasmospunk** [comment]
I saw the `impl Zeroize for Scalar` so for now we can close this.
