### ISSUE TITLE
Handle LMDB memory map resize

### ISSUE THREAD

**Issue by iljakuklic** [mintlayer/mintlayer-core#483]
LMDB map resizes are now treated as errors. This should be instead handled properly by resizing the memoy map and restarting all the involved transactions.

E.g. monero does it as follows: https://github.com/monero-project/monero/blob/fc907a957078cae2dc68348886a33363848dd089/src/blockchain_db/lmdb/db_lmdb.cpp#L494

**Comment by TheQuantumPhysicist** [comment]
This is done in #648 and others.
