### ISSUE TITLE
Get rid of index field access in mempool newtypes

### ISSUE THREAD

**Issue by royster57** [mintlayer/mintlayer-core#486]
It isn't related to your pull request, but I find this "index field access" somewhat confusing: I immediately want to check why it is a tuple and why only one field is utilized. Our `newtype` macro generates the `Deref` implementation, but `*ancestor_ids.into_iter()` breakes the type inference. Maybe we want to add a method such as `inner` to the `newtype` macro or is it only me who is frustrated in such cases?

_Originally posted by @stanislav-tkach in https://github.com/mintlayer/mintlayer-core/pull/482#discussion_r994860548_

**Comment by TheQuantumPhysicist** [comment]
This has already been fixed. The member in `newtype` is private now.
