### ISSUE TITLE
p2p constants refactoring

### ISSUE THREAD

**Issue by stanislav-tkach** [mintlayer/mintlayer-core#518]
We have some duplicated constants in libp2p and mock backends and most of these constants should be moved to the p2p config anyway.

**Comment by TheQuantumPhysicist** [comment]
@stanislav-tkach Is this over since we don't use libp2p anymore?

**Comment by stanislav-tkach** [comment]
I think there are still constants present that should be moved in the config. Additionally some of them are duplicated in different crates. For example, the `HEADER_LIMIT` is present in both chainstate and p2p.
