### ISSUE TITLE
Decompose big mempool impl block into smaller pieces

### ISSUE THREAD

**Issue by royster57** [mintlayer/mintlayer-core#523]
This is a huge implementation block that can probably be broken into smaller pieces. But not in this PR. Once you merge this PR, you can do this next.

_Originally posted by @TheQuantumPhysicist in https://github.com/mintlayer/mintlayer-core/pull/505#discussion_r1007174841_

**Comment by TheQuantumPhysicist** [comment]
Please do this next.

**Comment by TheQuantumPhysicist** [comment]
This has been already resolved.
