### ISSUE TITLE
Write a python script to replace cargo-deny

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#590]
The script has to do two things:

1. Ensure that all our crates use the same version of every crate in them (not the whole dependency tree like deny does), unless an exception is made in a list
2. Ensure that all licenses are allowed, and crates with manifest files with no licenses should produce an error

Cargo-deny was removed in PR #589, after it became unmaintainable, causing issues with every update we do.

A bonus thing cargo-deny did was finding vulnerabilities, but dependabot on github does that as well automatically.

**Comment by iljakuklic** [comment]
Addressed in #598

**Comment by muursh** [comment]
@iljakuklic your PR doesn't address the license bit yet.

**Comment by iljakuklic** [comment]
Dammit I did not notice you re-opened this issue @muursh. Given there is now a replacement issue for the license check alone, I will close this one again. Sorry for the chaos.
