### ISSUE TITLE
Prevent bloated peer information

### ISSUE THREAD

**Issue by stanislav-tkach** [mintlayer/mintlayer-core#594]
The `PeerInfo` structure has some fields of a non-fixed size, such as `agent`, `protocols` and `subscriptions`. There should be a limit for maximum peer info size.

**Comment by pavel-kokolemin** [comment]
Small update:
- `protocols` field was removed some time ago.
- `subscriptions` are stored in `BTreeSet` and are bounded in size (because there are only 3 distinct values).
So only the only unbounded field there is `agent`.
