### ISSUE TITLE
Add a crate license check

### ISSUE THREAD

**Issue by iljakuklic** [mintlayer/mintlayer-core#599]
Cargo-deny was removed in PR https://github.com/mintlayer/mintlayer-core/pull/589, after it became unmaintainable, causing issues with every update we do.

A bonus thing cargo-deny did was finding vulnerabilities, but dependabot on github does that as well automatically.

Some `cargo-deny` functionality, namely checking duplicate crate versions, was addressed in  #598. However, the license check still needs to be developed.

**Comment by Ivansete** [comment]
Hi @muursh, @iljakuklic ,

I've been checking this issue and I think there are two interesting options for that. You may already had reviewed them but I share just in case:

https://github.com/nexB/scancode-toolkit
https://crates.io/crates/cargo-license

What would be the best option and how you expect it to behave?

**Comment by iljakuklic** [comment]
> Hi @muursh, @iljakuklic ,
> 
> I've been checking this issue and I think there are two interesting options for that. You may already had reviewed them but I share just in case:
> 
> https://github.com/nexB/scancode-toolkit https://crates.io/crates/cargo-license
> 
> What would be the best option and how you expect it to behave?

Hi @Ivansete, thank you for looking into this.

As far as I can tell, the tools you linked inspect licenses of dependencies. While that is a useful piece of functionality, this issue is mainly concerned with checking the value of the `license` field in `Cargo.toml` files of crates in *this repo*, not external dependencies. Could the tools be employed to do that too?

I originally thought it would be done by a simple check in `.github/scripts/codecheck.py` which already contains a number of ad-hoc lints looking for minor code issues and omissions that are not already covered by `clippy` and similar tools. However, suggestions regarding alternative approaches are welcome too though.

**Comment by muursh** [comment]
I'd argue we're aiming to do both.

**Comment by iljakuklic** [comment]
> I'd argue we're aiming to do both.

That's fair. We may, however, have to treat them as separate issues if there is not a tool that handles both. Did we use to check both with `cargo-deny`?

**Comment by muursh** [comment]
`cargo-deny` was used to catch issues in dependencies, essentially the same thing being proposed here.

**Comment by Ivansete** [comment]
@iljakuklic - why `cargo deny` became unmaintainable?

**Comment by iljakuklic** [comment]
> @iljakuklic - why `cargo deny` became unmaintainable?

The main motivation was for it to check possible duplication of the `parity_scale_codec` crate if it's pulled in through multiple dependency paths. It's because possible differences in encoding may result in the network failing to achieve consensus resulting in a fork. However it checked for duplicate crates too aggressively and more and more crates had to be added to a whitelist. Eventually, the whitelist grew unbearably large.

Now we have an alternative approach to check scale codec duplication using a custom script. Maybe `cargo-deny` could be resurrected with duplicate crate checking switched off (can it be done?). That way, we would not get endlessly growing duplication whitelist while still being able to take advantage of the other features. Not sure if that's possible. Thoughts?

**Comment by Ivansete** [comment]
Hi @iljakuklic, thanks for your comments.

There is the [multiple versions config attribute](https://github.com/EmbarkStudios/cargo-deny/blob/05e1b34a1bb4926020ef70b85228031b2bdddd03/docs/src/checks/bans/cfg.md#the-multiple-versions-field-optional) ([bans] section) that seems to disable the duplicate-crate-checking.

On the other side, I add some more detail regarding the two options I mentioned in my first comment:

- https://github.com/nexB/scancode-toolkit --> this is suitable for local licences only (not dependency)
- https://crates.io/crates/cargo-license --> this is quite interesting and gives a sumup of the dependencies. It can get a JSON file with all the dependencies and their licenses. Maybe interesting for manual validation. 
usage example: `cargo license --manifest-path Cargo.toml --all-features -j`

**Comment by muursh** [comment]
Yep looks like `cargo deny check licenses` will run the licenses check. Having just run it we also get license checks against the subsystems in the repo as they're technically dependencies given how the code it designed, I forgot about that. We can probably rely on `cargo-deny` alone.

@Ivansete I don't know if you want to open a pr to reintroduce this?

**Comment by Ivansete** [comment]
Morning guys,

@muursh - I will raise a PR asap with the proposal and we carry on the discussion there.

**Comment by muursh** [comment]
Thanks :)

**Comment by Ivansete** [comment]
Hi @muursh @iljakuklic , while trying to push some changes I came across a permission issue.
May kindly provide me with writing rights please so that I can create new branch and issue the PR?

![image](https://user-images.githubusercontent.com/53038020/216777184-bc227d22-6d12-48c7-8fcf-bc61b6c97a43.png)

This can be done on Monday of course :)

**Comment by muursh** [comment]
@Ivansete can you fork the repo and create in your changes in a branch in your copy then create a pull request from your fork? That will fix the permissions issue you're facing. If you need a feel tips [this talks about forks](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and [this talks about creating PRs from forks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Hopefully those links will be clear if you need them, if not feel free to comment here again and one of us will try and help you through it.

We'll update the contributors file to make the process more explicit for external contributors.
