### ISSUE TITLE
Decide when to disconnect stalling peers

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#700]
Bitcoin uses `m_headers_sync_timeout` and `m_stalling_since` to decide when to do this. We currently only wait for peers to respond to pings. We should study this further when p2p is ready.

**Comment by TheQuantumPhysicist** [comment]
Isn't this already implemented, @pavel-kokolemin ?

**Comment by pavel-kokolemin** [comment]
Right, the peers are disconnected after the 5 second timeout if no header or block is received.
