### ISSUE TITLE
`allow_private_ips` flag in `TransportAddress`

### ISSUE THREAD

**Issue by pavel-kokolemin** [mintlayer/mintlayer-core#714]
There was some code duplication in `PeerManager` and the DNS server regarding the validation of announced addresses. When we receive network address announcements, we should check that the IP is valid (we should not allow 127.0.0.1 to be announced , for example). And the same check should be done in `PeerManager` and the DNS server.  To remove the code duplication, I moved the check to `TransportAddress::from_peer_address` (this required adding the `allow_private_ips` flag):
```
/// Allow working with abstract socket address types.
/// For example change socket port or encode for sending on wire.
/// It's might better to completely replace abstract socket types with PeerAddress.
pub trait TransportAddress: Sized {
    /// Convert abstract socket address to concrete type (PeerAddress)
    fn as_peer_address(&self) -> PeerAddress;

    /// Try get address back from PeerAddress.
    ///
    /// This may fail if the address is invalid or from another transport.
    fn from_peer_address(address: &PeerAddress, allow_private_ips: bool) -> Option<Self>;
}
```
It works, but is not a very clean solution.

**Comment by TheQuantumPhysicist** [comment]
I suppose we can close this since that generic was removed, right?

**Comment by pavel-kokolemin** [comment]
Right.
