### ISSUE TITLE
Peer permissions

### ISSUE THREAD

**Issue by stanislav-tkach** [mintlayer/mintlayer-core#731]
Peer permissions should be added allowing things such as requesting headers during initial block download or not being banned/disconnected for misbehavior.

**Comment by TheQuantumPhysicist** [comment]
I wouldn't call this "permissions", but "peer types". There's another issue for this.

**Comment by stanislav-tkach** [comment]
Closed in favor of https://github.com/mintlayer/mintlayer-core/issues/621.
