### ISSUE TITLE
Implement a proper ban score for mempool errors

### ISSUE THREAD

**Issue by stanislav-tkach** [mintlayer/mintlayer-core#770]
Not every mempool TxValidationError error means that the transaction was malicious, double-spends may happen due to a minor reorg and a peer shouldn't be punished in such cases. Perhaps this can be done by implementing the `BanScore` trait for the `TxValidationError` error.

**Comment by TheQuantumPhysicist** [comment]
The decision on banning should be decided in the mempool with its own logic.
