### ISSUE TITLE
Limit difficulty swings for PoS retargeting

### ISSUE THREAD

**Issue by azarovh** [mintlayer/mintlayer-core#787]
Difficulty change should be limited in a way to prevent high spikes.
Bitcoin for example limits timespan by factor of 4 (https://github.com/bitcoin/bitcoin/blob/master/src/pow.cpp#L56). 

For us, this approach might not be good enough because we adjust difficulty on every block, so the limiting function should be more smooth as well.

**Comment by alfiedotwtf** [comment]
I think we already do this in `common/src/chain/pow.rs:max_retarget_factor()`.

**Comment by TheQuantumPhysicist** [comment]
> I think we already do this in `common/src/chain/pow.rs:max_retarget_factor()`.

This issue is meant for PoS, not PoW.
