### ISSUE TITLE
Improve the p2p subsystem creation

### ISSUE THREAD

**Issue by stanislav-tkach** [mintlayer/mintlayer-core#889]
Currently the intermediate `P2pInit` structure is returned from the `make_p2p` function. Also the subsystem creation requires a custom event loop:
```rust
let p2p: P2pInit = make_p2p(
        Arc::clone(&chain_config),
        p2p_config,
        chainstate.clone(),
        mempool.clone(),
        Default::default(),
        peerdb_storage,
    )
    .unwrap();
    let p2p = manager.add_subsystem_with_custom_eventloop("p2p", {
        move |call, shutdown| p2p.run(call, shutdown)
    });
``` 
This is required because of the two reasons:
1. The `P2p` structure is generic over the transport and the concrete transport is chosen based on runtime parameters, so it is impossible to return it from a function directly, only as `Box<dyn P2pInterface>`.
2. P2p requires a specific shutdown logic, but it cannot be placed in the `Subsystem::shutdown` function because the `Subsystem` trait is implemented for `Box<dyn P2pInterface>` and not for the `P2p` structure directly.

Ideally neither the custom event loop nor the `P2pInit` structure should be needed, and the shutdown logic should be moved to the implementation of the `Subsystem` trait for `P2p`.

**Comment by TheQuantumPhysicist** [comment]
I'm closing this as unnecessary. We may change our minds later, but for now it's fine.
