### ISSUE TITLE
Wallet improvement tasks

### ISSUE THREAD

**Issue by OBorce** [mintlayer/mintlayer-core#931]
A list of improvements to be done for the Wallet:

- [x] Coin selector - to select which UTXOs to use when transferring ~~to minimize fees~~
- [x] Fix derivation of VRF private keys https://github.com/mintlayer/mintlayer-core/issues/929
- [x] Create a controller function that returns pool id(s)
- [x] support lock then transfer
- [x] transaction/network fee calculation - need to calculate proper fee for the transaction
- [x] wallet recovery from seed phrase - given a seed phrase recover the accounts and keys in usage
- [x] support writing/restoring the seed phrase from the database. Currently only the root key is stored.
- [x] additional/multiple account creation wallet command - follow BIP44
- [x] support issuance and transfer of tokens & NFTs
- [x] Argon2 algorithm parameter research for default values (mentioned in #914)
- [x] Create functional tests that utilize the wallet's file/stdin feature to test the wallet
- [x] After creating a transaction by the wallet and submitting it, store the change done by that transaction in the wallet, so that new transaction can be created based on the new state after that transaction (this doesn't necessarily refer to the mempool specifically, but transactions that are not yet broadcast. An assumption has to be made about the new state of UTXOs, otherwise it won't be possible to create more than one transaction in a block) (based on that, abandoning transactions also should be supported)
- [x] Save the ChainConfig's chain-type, so that wallets only work on their designated blockchain
- [x] Add support for Account balances in the wallet, and allow using them when creating transactions
- [x] Add support for showing Locked Balance in the wallet
- [x] Function in the controller to rescan the blockchain
- [x] New wallets shouldn't do a rescan at all from block zero. They should be assumed to be empty.
- [x] fix wallet account syncing order
- [x] refactor the wallet initialization to ensure that functions aren't called in an invalid state
- [x] update delegation and pool balances with block rewards

**Comment by pavel-kokolemin** [comment]
There is one more important task - proper support for mempool transactions. The wallet should be able to show zero-conf balance and handle ZC UTXOs properly. Right now we can only do one transaction per block (waiting for a new block after sending a transaction), which is very annoying.

>  support writing/restoring the seed phrase from the database. Currently only the root key is stored.

Are you sure about this? @TheQuantumPhysicist said that storing the derived root key is done on purpose for a better security (currently we store the root key, but it should be the mintlayer's key `m/44'/19788'`). Personally, I would prefer to allow making mnemonic backups at any time.

**Comment by pavel-kokolemin** [comment]
Also @TheQuantumPhysicist said that it would be better to use hard derivation. I don't know how much this can complicate the code.

**Comment by pavel-kokolemin** [comment]
And there is one more TODO in the code:
```
// TODO wallet should save the chain config
```
I think it's also important because right now a Testnet wallet could be loaded as a Mainnet wallet, which obviously won't work properly.

**Comment by TheQuantumPhysicist** [comment]
> Also @TheQuantumPhysicist said that it would be better to use hard derivation. I don't know how much this can complicate the code.

I don't remember the motivation, but I'm OK with postponing this for now.

**Comment by TheQuantumPhysicist** [comment]
Done.
