### ISSUE TITLE
Get rid of manually specifying the VERSION byte in transactions and blocks

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mintlayer/mintlayer-core#94]
The enum that contains a transaction version should handle this. However, this needs some thought because of how we wanna implement the `Idable` trait the internal versioned Transaction. Ideally, we never have to write the version byte manually, but it should come with from the enum. This is a low priority issue for now, but its time should come sooner or later.

**Comment by iljakuklic** [comment]
The version byte is now handled by the inner versioned struct. As far as I know, there are no longer any duplicate manual version numbers. Could this be considered addressed by #223 @TheQuantumPhysicist?

**Comment by TheQuantumPhysicist** [comment]
Yep. This is resolved.
