### ISSUE TITLE
Fix `mainnet_schedule_table`

### ISSUE THREAD

**Issue by pavel-kokolemin** [mintlayer/mintlayer-core#955]
`mainnet_schedule_table` is configured for 1 minute blocks while we use 2 minute blocks by default.

**Comment by TheQuantumPhysicist** [comment]
Anyone reading this, please check my math, as I think there's nothing wrong with the current schedule.

The supply plan is: 400M pre-mine + 200M emitted over 10 years through staking.

The current schedule in `mainnet_schedule_table` (block subsidy/block in the nth year) is:
```
[202, 151, 113, 85, 64, 48, 36, 27, 20, 15, 0]
```

The number of blocks per year is: `365x24x60x60/120=262800`

If we multiply that number by the `mainnet_schedule_table` elements, and sum, we get `199 990 800`, which is around 200M.

I'm closing this issue as there's nothing wrong with the emission schedule. Please correct me if I'm wrong.
