### ISSUE TITLE
Swap out the handrolled Mempool mock for a mockall implementation

### ISSUE THREAD

**Issue by alfiedotwtf** [mintlayer/mintlayer-core#957]
If I remember correctly, the reason I created the hand-rolled Mempool mock was because there were circular dependancies within `blockprod` pulling in `chainstate` and `mempool`. which was one of the reasons why the mocks were moved to `/mocks/`. However after @ImplOfAnImpl's discussion on Atomics, it made me have another look at the Mempool mock given that there are a lot of Atomics in there.

I have a local change which implements the Mempool mock using `mockall`, which seems to now work within `blockprod`. I'm creating the issue as a reminder to update `blockprod` tests with the `mockall` `Mempool` implementation.

**Comment by TheQuantumPhysicist** [comment]
Done
