### ISSUE TITLE
Create better abstractions for unit tests with PoS in chainstate

### ISSUE THREAD

**Issue by azarovh** [mintlayer/mintlayer-core#972]
Tests with PoS are very complicated and hard to both write and debug. We need better abstractions to simplify this process

**Comment by TheQuantumPhysicist** [comment]
Please elaborate

**Comment by azarovh** [comment]
It requires tons of manipulations with vrfs, kernels, singatures etc. I'd like to see the process of creating a block simplified and encapsulated as much as possible.

`pos_processing_test.rs` is the suite that bothers me and consumes time when something goes wrong. 

I don't have particular suggestions but a good point to start is to look at `mine_pos_block` function that Pavel added.
