### ISSUE TITLE
Replace UpgradeVersion with ConsensusUpgrade

### ISSUE THREAD

**Issue by alfiedotwtf** [mintlayer/mintlayer-core#992]
Seeing as `UpgradeVersion::SomeUpgrade` isn't used anywhere, we can possibly promote `ConsensusUpgrade(ConsensusUpgrade)` in place of `UpgradeVersion`.

**Comment by TheQuantumPhysicist** [comment]
This is just a placeholder which will be used in hard forkes. Nothing is wrong there.
