### ISSUE TITLE
Clean up the usage of atomics throughout the codebase

### ISSUE THREAD

**Issue by ImplOfAnImpl** [mintlayer/mintlayer-core#999]
Atomics are somewhat overused in the codebase right now. In particular, many of them are wrapped in Arc and then shared across structs and modules.
Recently, "simplified" atomic types have been introduced to ensure that such shared atomics at least use consistent memory orderings. They come in 3 "flavours" - `RelaxedAtomic`s, which are mostly used as a way to pacify the borrow checker, as well as `AcqRelAtomic`s and `SeqCstAtomic`s, which are synchonization primitives.
So:
1) `AcqRelAtomic` and `SeqCstAtomic` are still a half measure. Ideally, they should be replaced with higher-level synchronization primitives.
2) Sometimes `AcqRelAtomic` and `SeqCstAtomic` are used in places where they are not strictly required, just "for the extra peace of mind". Right now the choice between `AcqRelAtomic` and `SeqCstAtomic` in cases like that is sometimes made rather arbitrarily. Perhaps we should choose one of them as the "reasonable safe default". Secondly, if the default is chosen, perhaps the other variant of the "simplified" atomic should be removed. This makes sense, because situations when the "reasonable" default is not reasonable enough are definitely not simple, so if this is the case, perhaps the developer should use the standard atomic types with explicit memory orderings, while making sure that they are properly encapsulated.

**Comment by TheQuantumPhysicist** [comment]
@ImplOfAnImpl Is this considered fixed now? You did wrap atomics and I got rid of the atomic in block production for PoS time stamps.

**Comment by TheQuantumPhysicist** [comment]
This is closed in favor of #1254, which specifies the remaining case. In general we'll try to get rid of atomics as we go.
